//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityChange
    {
        public int EntityChangeId { get; set; }
        public int RevisionId { get; set; }
        public int EntityId { get; set; }
        public string ChangeTypeCode { get; set; }
        public string NewName { get; set; }
        public string OldName { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Revision Revision { get; set; }
    }
}
