//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldChange
    {
        public int FieldChangeId { get; set; }
        public int EntityFieldId { get; set; }
        public string FieldChangeTypeCode { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public int RevisionId { get; set; }
    
        public virtual FieldChangeType FieldChangeType { get; set; }
        public virtual EntityField EntityField { get; set; }
        public virtual Revision Revision { get; set; }
    }
}
