//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIManager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjManEntities : DbContext
    {
        public ProjManEntities()
            : base("name=ProjManEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityField> EntityFields { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<PathType> PathTypes { get; set; }
        public virtual DbSet<ProjectPath> ProjectPaths { get; set; }
        public virtual DbSet<DataType> DataTypes { get; set; }
        public virtual DbSet<EntityChange> EntityChanges { get; set; }
        public virtual DbSet<EntityLink> EntityLinks { get; set; }
        public virtual DbSet<LinkType> LinkTypes { get; set; }
        public virtual DbSet<LinkChange> LinkChanges { get; set; }
        public virtual DbSet<EnvironmentType> EnvironmentTypes { get; set; }
        public virtual DbSet<ProjectDatabase> ProjectDatabases { get; set; }
        public virtual DbSet<FieldChange> FieldChanges { get; set; }
        public virtual DbSet<FieldChangeType> FieldChangeTypes { get; set; }
    }
}
