//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revision()
        {
            this.EntityChanges = new HashSet<EntityChange>();
            this.LinkChanges = new HashSet<LinkChange>();
            this.FieldChanges = new HashSet<FieldChange>();
        }
    
        public int RevisionId { get; set; }
        public int ProjectId { get; set; }
        public string RevisionName { get; set; }
        public System.DateTime BeginDate { get; set; }
        public string RevisionStatusCode { get; set; }
        public Nullable<System.DateTime> CommitDate { get; set; }
        public string ScriptFilename { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityChange> EntityChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkChange> LinkChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldChange> FieldChanges { get; set; }
    }
}
