//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template()
        {
            this.TemplateEntityAttributes = new HashSet<TemplateEntityAttribute>();
            this.TemplateGroupMembers = new HashSet<TemplateGroupMember>();
        }
    
        public int TemplateId { get; set; }
        public string TemplateName { get; set; }
        public string FileMask { get; set; }
        public string PathMask { get; set; }
        public string CodeProjectTypeCode { get; set; }
        public string LanguageTypeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateEntityAttribute> TemplateEntityAttributes { get; set; }
        public virtual CodeProjectType CodeProjectType { get; set; }
        public virtual LanguageType LanguageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateGroupMember> TemplateGroupMembers { get; set; }
    }
}
